CREATE TABLE public.password_reset_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ON public.password_reset_tokens (user_email);
CREATE INDEX ON public.password_reset_tokens (expires_at);