// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hymspnpiouwigttsaqct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5bXNwbnBpb3V3aWd0dHNhcWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzA3MTMsImV4cCI6MjA2NzEwNjcxM30.z-r7Tx6ocS5H-JcdZ7NJIoHXAVTV_FfG0K332i4mw00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});