// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://lrsypwazusmltkhkswrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxyc3lwd2F6dXNtbHRraGtzd3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTIxNjYsImV4cCI6MjA3NDYyODE2Nn0.KNBIP-xuq2ofGT810TR0LRHtuwc_WWpR9nwh_ZU9bEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});